export const products = [
    {
        id: "1001",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1002",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1003",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1004",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1005",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1006",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1007",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1008",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
    {
        id: "1009",
        product_name: "Coombes",
        product_collection: "Lounge",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: 2,
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR1aFegVu8ju1c5rLUOaF-WBUuawhEUFiwSnBB600OWYAfk5Z-T6DhP4kVT90cCmpmm39Ijk-d1DYcvAf1C2nDU3_tclxjxEgBjjf4_IWMVjYGz9TAfXAf",
    },
]