export const products = [
    {
        id: "1001",
        product_name: "Coombes",
        product_collection: "Coombes",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: "black,yellow",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1002",
        product_name: "Coombes",
        product_collection: "Keeve Set",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 3,
        color_options: "white",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1003",
        product_name: "Coombes",
        product_collection: "Keeve Set",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 1,
        color_options: "black,white,yellow",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1004",
        product_name: "Coombes",
        product_collection: "Momo",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 5,
        color_options: "darkgrey",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1005",
        product_name: "Coombes",
        product_collection: "Kappu",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 4,
        color_options: "yellow,white",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1006",
        product_name: "Coombes",
        product_collection: "Coombes",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 5,
        color_options: "darkgrey,white,black",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1007",
        product_name: "Coombes",
        product_collection: "Kappu",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 2,
        color_options: "black",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1008",
        product_name: "Coombes",
        product_collection: "Keeve Set",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 3,
        color_options: "yellow,darkgrey",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
    {
        id: "1009",
        product_name: "Coombes",
        product_collection: "Coombes",
        product_category: "Sofa",
        product_desc: "This is product description",
        star_rating: 0,
        color_options: "yellow",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
    },
]