export const products = [
    {
        id: "1001",
        product_name: "Astride Ace Mid Black",
        product_collection: "Coombes",
        product_category: "Table & Chair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 4,
        color_options: "black,yellow",
        product_price: 2600,
        product_sell_price: 2400,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71bM4pB6KGL._SX679_.jpg",
    },
    {
        id: "1002",
        product_name: "Uberlyfe 3 Bare",
        product_collection: "Keeve Set",
        product_category: "Armchair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 3,
        color_options: "darkgreen",
        product_price: 1800,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71eK6fgPXbL._SX679_.jpg",
    },
    {
        id: "1003",
        product_name: "CubiCubi Desk",
        product_collection: "Keeve Set",
        product_category: "Side Table",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 1,
        color_options: "black,darkgreen,yellow",
        product_price: 1999,
        product_sell_price: 1777,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71bjDRu7k9L._SX679_.jpg",
    },
    {
        id: "1004",
        product_name: "UrbanCart Relax Bamboo",
        product_collection: "Momo",
        product_category: "Armchair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 5,
        color_options: "darkgrey,darkgreen,yellow,black",
        product_price: 1200,
        product_sell_price: 1099,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71bXojr71ML._SX679_.jpg",
    },
    {
        id: "1005",
        product_name: "Extend Crafts",
        product_collection: "Kappu",
        product_category: "Shelves",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 4,
        color_options: "yellow,darkgreen",
        product_price: 699,
        product_sell_price: 599,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/61HyE1Yj3SL._SX679_.jpg",
    },
    {
        id: "1006",
        product_name: "Savya Home Apollo",
        product_collection: "Coombes",
        product_category: "Table & Chair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 5,
        color_options: "darkgrey,darkgreen,black",
        product_price: 5999,
        product_sell_price: 2499,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/81Xe36n9YzL._SX679_.jpg",
    },
    {
        id: "1007",
        product_name: "Luxzer 6",
        product_collection: "Kappu",
        product_category: "Shelves",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 2,
        color_options: "black",
        product_price: 900,
        product_sell_price: 599,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71CSJON4FZL._SX679_.jpg",
    },
    {
        id: "1008",
        product_name: "The Sleep Company Luxe",
        product_collection: "Keeve Set",
        product_category: "Armchair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 3,
        color_options: "yellow,darkgrey",
        product_price: 3999,
        product_sell_price: 1899,
        product_quantity: 2,
        product_thumb: "https://thesleepcompany.in/cdn/shop/files/2_1558bd96-e9d7-48ea-b366-6e76d8a03fe5.jpg?v=1721586756&width=1445",
    },
    {
        id: "1009",
        product_name: "Green Soul Seoul",
        product_collection: "Coombes",
        product_category: "Table & Chair",
        product_desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        star_rating: 2,
        color_options: "yellow",
        product_price: 10999,
        product_sell_price: 8599,
        product_quantity: 2,
        product_thumb: "https://m.media-amazon.com/images/I/71wqxn2Ox+L._SX679_.jpg",
    },
]